# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username
# patreon: # Replace with your Patreon username
# open_collective: psdl
# ko_fi: # Replace with your Ko-fi username
# tidelift: # npm/package-name
# community_bridge: # Replace with your community bridge project name
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# otechie: # Replace with your Otechie username
# lfx_crowdfunding: # Replace with your LFX project name
custom: # Replace with up to 4 custom sponsorship URLs
