"""
Auto-generated Python types from spec/schema.json
Generated: 2025-12-11T16:30:38.291011

DO NOT EDIT - Regenerate with: python tools/codegen.py --types
"""

# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-12-11T21:30:38+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

ScenarioName: TypeAlias = str


SemanticVersion: TypeAlias = str


Identifier: TypeAlias = str


@dataclass
class PopulationFilter:
    include: list[str] | None = None
    exclude: list[str] | None = None


class SignalType(Enum):
    numeric = "numeric"
    categorical = "categorical"
    boolean = "boolean"
    datetime = "datetime"


class OMOPDomain(Enum):
    measurement = "measurement"
    condition = "condition"
    drug = "drug"
    procedure = "procedure"
    observation = "observation"
    device = "device"
    specimen = "specimen"


TrendExpression: TypeAlias = str


LogicExpression: TypeAlias = str


class SeverityLevel(Enum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


@dataclass
class ConceptMapping:
    concept_id: int | None = None
    table: str | None = None
    value_column: str | None = None
    datetime_column: str | None = None


class ValidationStatus(Enum):
    draft = "draft"
    validated = "validated"
    clinical_review = "clinical_review"
    production = "production"


@dataclass
class ScenarioMetadata:
    created: str | None = None
    updated: str | None = None
    references: list[str] | None = None
    validation_status: ValidationStatus | None = None
    icd10_codes: list[str] | None = None
    snomed_codes: list[str] | None = None


Window: TypeAlias = str


class WindowedOperator(Enum):
    delta = "delta"
    slope = "slope"
    sma = "sma"
    ema = "ema"
    min = "min"
    max = "max"
    count = "count"
    first = "first"
    std = "std"
    stddev = "stddev"
    percentile = "percentile"


class PointwiseOperator(Enum):
    last = "last"
    exists = "exists"
    missing = "missing"


class ComparisonOperator(Enum):
    field__ = "=="
    field___1 = "!="
    field_ = "<"
    field___2 = "<="
    field__1 = ">"
    field___3 = ">="


class BooleanOperator(Enum):
    AND = "AND"
    OR = "OR"
    NOT = "NOT"


@dataclass
class SignalSpec1:
    source: str
    type: SignalType | None = SignalType.numeric
    concept_id: int | None = None
    unit: str | None = None
    domain: OMOPDomain | None = OMOPDomain.measurement
    description: str | None = None


SignalSpec: TypeAlias = str | SignalSpec1


@dataclass
class TrendSpec1:
    expr: TrendExpression
    description: str | None = None


TrendSpec: TypeAlias = TrendExpression | TrendSpec1


@dataclass
class LogicSpec1:
    expr: LogicExpression
    severity: SeverityLevel | None = None
    description: str | None = None
    recommendation: str | None = None


LogicSpec: TypeAlias = LogicExpression | LogicSpec1


@dataclass
class MappingConfig:
    source: str | None = None
    inline: dict[str, ConceptMapping] | None = None


SignalDefinitions: TypeAlias = dict[str, SignalSpec]


TrendDefinitions: TypeAlias = dict[str, TrendSpec]


LogicDefinitions: TypeAlias = dict[str, LogicSpec]


@dataclass
class PsdlScenarioSchemaV02:
    scenario: ScenarioName
    version: SemanticVersion
    signals: SignalDefinitions
    logic: LogicDefinitions
    name: str | None = None
    description: str | None = None
    author: str | None = None
    tags: list[str] | None = None
    population: PopulationFilter | None = None
    trends: TrendDefinitions | None = None
    mapping: MappingConfig | None = None
    metadata: ScenarioMetadata | None = None
